# Generated by Django 3.1.7 on 2021-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
