# Generated by Django 3.1.7 on 2021-03-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='programsTags',
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(to='blog_app.Tag'),
        ),
    ]
