# Generated by Django 3.1.7 on 2021-03-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_tag_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
