# Generated by Django 3.1.7 on 2021-03-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210315_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='programs',
            new_name='programy',
        ),
    ]
