# Generated by Django 3.1.7 on 2021-03-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210315_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(related_name='programs', to='blog_app.Tag'),
        ),
    ]
