# Generated by Django 3.1.7 on 2021-03-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20210313_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Program',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='programs',
            field=models.ManyToManyField(to='blog_app.Program'),
        ),
    ]
