# Generated by Django 3.1.7 on 2021-03-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20210323_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='galleries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.gallery', verbose_name='Galerie'),
        ),
    ]
