# Generated by Django 3.1.7 on 2021-03-16 13:17

import blog_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20210315_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=200, validators=[blog_app.validators.check_length]),
        ),
    ]
