# Generated by Django 3.1.7 on 2021-03-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20210323_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='aplications',
            new_name='applications',
        ),
    ]
