# Generated by Django 3.1.7 on 2021-04-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20210408_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
