# Generated by Django 3.1.7 on 2021-04-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_auto_20210409_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
